sudo: false

cache:
  apt: true
  ccache: true

# Use YAML anchors (&) and aliases (*) to more easily define
# a product of build configurations by merging the env tables into a predefined
# table (<<:)
yaml_aliases:
    - &base_linux_config
      os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - g++-7
            - cmake
            - cmake-data
            - gdb
            - apport
            #- python3
            #- python
          sources:
            - ubuntu-toolchain-r-test

language: generic
matrix:
  include:
    - <<: *base_linux_config
      env:
        - CMAKE_CC="gcc-7"
        - CMAKE_CXX="g++-7"
        - COMPILER_NAME=gcc
        - CXX=g++-7
        - CC=gcc-7
        - BUILDMODE=Debug
    - <<: *base_linux_config
      env:
        - CMAKE_CC="gcc-7"
        - CMAKE_CXX="g++-7"
        - COMPILER_NAME=gcc
        - CXX=g++-7
        - CC=gcc-7
        - BUILDMODE=Release

script:
  - git submodule sync && git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DPWM_ENABLE_CILK_ALGORITHM=OFF -DCMAKE_BUILD_TYPE=$BUILDMODE ..
  - make check
  - make
