sudo: false

cache:
  apt: true
  ccache: true

language: generic
matrix:
  include:
    - os: linux
      env:
        - COMPILER_NAME=gcc
        - CXX=g++-6
        - CC=gcc-6
      dist: trusty
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - cmake-data
            - gdb
            - apport
            #- python3
            #- python
          sources:
            - ubuntu-toolchain-r-test

script:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake ..
  - make bit_copy
  - make build_check
  - cd test
  - ulimit -c unlimited -S
  - ./wm_dd_pc_test_testrunner || RESULT=$?
  - ls -l
  - if [[ ${RESULT} != 139 ]]; then echo "expected segfault and 139 exit but instead exited with ${RESULT}" && exit 1; fi;
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb $(pwd)/wm_dd_pc_test_testrunner core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;


#  - make
