sudo: false

cache:
  apt: true
  ccache: true

language: generic
matrix:
  include:
    - os: linux
      env:
        - COMPILER_NAME=gcc
        - CXX=g++-6
        - CC=gcc-6
      dist: trusty
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - cmake-data
            - gdb
            - apport
            #- python3
            #- python
          sources:
            - ubuntu-toolchain-r-test

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make check
  - make
