sudo: false

cache:
  apt: true
  ccache: true

language: generic
matrix:
  include:
    - os: linux
      env:
        - COMPILER_NAME=gcc
        - CXX=g++-6
        - CC=gcc-6
      dist: trusty
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - cmake-data
            - gdb
            - apport
            #- python3
            #- python
          sources:
            - ubuntu-toolchain-r-test

script:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake ..
  - make bit_copy
  - make build_check
  - cd test
  - ulimit -c unlimited -S
  - gdb wm_dd_pc_test_testrunner -ex "run" -ex "thread apply all bt" -ex "set pagination 0" -batch
  - ls -l

#  - make
