sudo: false

cache:
  apt: true
  ccache: true

env: NGROK_TOKEN=4M2AKLWu47WndvfUFN6Yv_6h2AeBxCSHAikHAXRj46x
before_install:
  - eval "$(curl -sL https://raw.github.com/fniephaus/travis-remote-shell/master/run.sh)"

language: generic
matrix:
  include:
    - os: linux
      env:
        - COMPILER_NAME=gcc
        - CXX=g++-6
        - CC=gcc-6
      dist: trusty
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - cmake-data
            #- python3
            #- python
          sources:
            - ubuntu-toolchain-r-test

script:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make bit_copy
  - make check
